### ISSUE TITLE
Separate Languages into Individual Files

### ISSUE THREAD

**Issue by jpyper** [lk-geimfari/awesomeo#3]
Just a thought... It might make it easier the make separate files for each language. Also, you could possibly turn this into a website using https://pages.github.com/ as a host.

This is just my 2 cents/pence/yen.

Feel free to close this issue without comment if you are not interested.

**Comment by lk-geimfari** [comment]
I'll do it as soon as possible. Thank you!

**Comment by lk-geimfari** [comment]
@jpyper It's done! da3e252
